sudo: required
services:
  - docker

script: 
  - docker build -t mmouru/node .
  - docker images mmouru/node

before_deploy:
  - docker login -u $USER -p $PASSWORD

deploy:
  provider: script
  script: docker push mmouru/node
  on:
    branch: master